# Generated by Django 4.1.1 on 2022-09-15 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_funcionario_imagem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="funcionario",
            old_name="instagran",
            new_name="instagram",
        ),
    ]
