# Generated by Django 4.1.1 on 2022-09-15 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_instagran_funcionario_instagram"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionario",
            name="bio",
            field=models.TextField(max_length=150, verbose_name="Bio"),
        ),
    ]
