# Generated by Django 4.1.1 on 2022-09-15 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_funcionario_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionario",
            name="bio",
            field=models.TextField(max_length=100, verbose_name="Bio"),
        ),
    ]
