# Generated by Django 4.1.1 on 2022-09-15 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_recurso"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Recurso",
        ),
    ]
